export const ME = 'ME';
export const ME_ERROR = 'ME_ERROR';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const DELETE_PRODUCT_MANY = 'DELETE_PRODUCT_MANY';
export const DELETE_PRODUCT_MANY_FAIL = 'DELETE_PRODUCT_MANY_FAIL';

export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL';

export const GET_TOPICS_COUNT = 'GET_TOPICS_COUNT';
export const GET_TOPICS_COUNT_FAIL = 'GET_TOPICS_COUNT_FAIL';

export const DELETE_TOPIC = 'DELETE_TOPIC';
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL';

export const DELETE_TOPIC_MANY = 'DELETE_TOPIC_MANY';
export const DELETE_TOPIC_MANY_FAIL = 'DELETE_TOPIC_MANY_FAIL';

export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_FAIL = 'GET_ROLES_FAIL';

export const GET_ADMINS = 'GET_ADMINS';
export const GET_ADMINS_FAIL = 'GET_ADMINS_FAIL';

export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

export const DELETE_ADMIN_MANY = 'DELETE_ADMIN_MANY';
export const DELETE_ADMIN_MANY_FAIL = 'DELETE_ADMIN_MANY_FAIL';

export const GET_COUPONS = 'GET_COUPONS';
export const GET_COUPONS_FAIL = 'GET_COUPONS_FAIL';

export const DELETE_COUPON = 'DELETE_COUPON';
export const DELETE_COUPON_FAIL = 'DELETE_COUPON_FAIL';

export const DELETE_COUPON_MANY = 'DELETE_COUPON_MANY';
export const DELETE_COUPON_MANY_FAIL = 'DELETE_COUPON_MANY_FAIL';

export const GET_PAYMENTS_COUNT = 'GET_PAYMENTS_COUNT';
export const GET_PAYMENTS_COUNT_FAIL = 'GET_PAYMENTS_COUNT_FAIL';

export const DELETE_PAYMENT = 'DELETE_PAYMENT';
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL';

export const DELETE_PAYMENT_MANY = 'DELETE_PAYMENT_MANY';
export const DELETE_PAYMENT_MANY_FAIL = 'DELETE_PAYMENT_MANY_FAIL';

export const GET_AGENTS = 'GET_AGENTS';
export const GET_AGENTS_FAIL = 'GET_AGENTS_FAIL';

export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';

export const GET_FOLLOWUPS = 'GET_FOLLOWUPS';
export const GET_FOLLOWUPS_FAIL = 'GET_FOLLOWUPS_FAIL';

export const POST_FOLLOWUP = 'POST_FOLLOWUP';
export const POST_FOLLOWUP_FAIL = 'POST_FOLLOWUP_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_CONTENTS = 'GET_CONTENTS';
export const GET_CONTENTS_FAIL = 'GET_CONTENTS_FAIL';

export const GET_CONTENT_DETAIL = 'GET_CONTENT_DETAIL';
export const GET_CONTENT_DETAIL_FAIL = 'GET_CONTENT_DETAIL_FAIL';

export const ADD_CONTENT = 'ADD_CONTENT';
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL';

export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const UPDATE_CONTENT_FAIL = 'UPDATE_CONTENT_FAIL';

export const PUT_TRANSFER_CONFIRMS = 'PUT_TRANSFER_CONFIRMS';
export const PUT_TRANSFER_CONFIRMS_FAIL = 'PUT_TRANSFER_CONFIRMS_FAIL';
